name: slides
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      # https://github.com/cypress-io/github-action
      - name: Test slides 🎞
        uses: cypress-io/github-action@v2
        with:
          config-file: 'cypress-slides.json'
          start: 'npm run slides'
          wait-on: 'http://localhost:3100'

      # build and deploy new version of the slides
      - name: Build slides 🏗
        run: npm run slides:build -- --base /cypress-workshop-basics/

      # TODO deploy to gh-pages
      - name: Deploy slides 📋
        run: ls -la dist
